### ISSUE TITLE
No such file or directory: 'train_list_path'

### ISSUE THREAD

**Issue by longeila** [chufengt/iccv19_attribute#70]
Traceback (most recent call last):
  File "main.py", line 515, in <module>
    main()
  File "main.py", line 56, in main
    train_dataset, val_dataset, attr_num, description = Get_Dataset(args.experiment, args.approach)
  File "/gpuapp/ALM-pedestrian-attribute/utils/datasets.py", line 189, in Get_Dataset
    train_dataset = MultiLabelDataset(root='data_path',
  File "/gpuapp/ALM-pedestrian-attribute/utils/datasets.py", line 15, in __init__
    labels = open(label).readlines()
FileNotFoundError: [Errno 2] No such file or directory: 'train_list_path'

dell@dell-Powe$ python main.py --approach=inception_iccv --experiment=rap

**Comment by chufengt** [comment]
replace `train_list_path ` with your actual data path
